# Generated by Django 2.1.2 on 2021-04-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Asset Group Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Group',
                'db_table': 'AssetGroup',
            },
        ),
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='Hostname')),
                ('outer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Outer IP')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Inner IP')),
                ('port', models.IntegerField(blank=True, default=22, null=True, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='Auth Password')),
                ('os', models.CharField(blank=True, max_length=64, null=True, verbose_name='OS')),
                ('os_release', models.CharField(blank=True, max_length=32, null=True, verbose_name='OS Release')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU Model')),
                ('cpu_count', models.IntegerField(null=True, verbose_name='CPU Count')),
                ('mem_total', models.CharField(blank=True, max_length=64, null=True, verbose_name='Memory Total')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Serial Number')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.AssetGroup', verbose_name='Asset Group')),
            ],
            options={
                'verbose_name': 'Asset Info',
                'verbose_name_plural': 'Asset Info',
                'db_table': 'AssetInfo',
            },
        ),
    ]
