# Generated by Django 2.1.2 on 2021-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210424_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='asset_sub_type',
            field=models.SmallIntegerField(choices=[(0, 'WDS_server'), (1, 'SF_server'), (2, 'Dome_server')], default=2, max_length=64, verbose_name='资产子类型'),
        ),
    ]
